升级表结构：

dev:
CREATE TABLE "YDZY_SEC_DEV"."CS_SALE_AUTH" 
TABLESPACE "DWDATA_62"

dat：
CREATE TABLE "YDZY_SEC_DAT"."CS_SB_INFO" 
TABLESPACE "DWDATA_62"


uat：

CREATE TABLE "YDZY_SEC_UAT"."CS_SB_INFO" 
TABLESPACE "DWDATA_64"

prd:
CREATE TABLE "YDZYSEC"."CLASSROOM_CHANNEL" 
TABLESPACE "WWDATA_INT"



ALTER TABLE "YDZY_SEC_DEV"."LI_ORD_ORDER" ADD (SB_LOCATION varchar2(32));
COMMENT ON COLUMN "YDZY_SEC_DEV"."LI_ORD_ORDER"."SBNO" IS '社保账号';
COMMENT ON COLUMN "YDZY_SEC_DEV"."LI_ORD_ORDER"."SB_LOCATION" IS '社保所在地';

Oracle删除一行：
ALTER TABLE "YDZY_SEC_DEV"."LI_ORD_ORDER" drop column SB_LOCATION2;


alter table asset_orders add remark varchar2(255);

