查看表索引：
show index from table

INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 0, 'PRIMARY', 1, 'ID', 'A', 1252251, NULL, NULL, '', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendriskcode_idx', 1, 'RISK_CODE', 'A', 2, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 1, 'AGE', 'A', 69, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 2, 'DURATION', 'A', 4802, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 3, 'INSUREYEAR', 'A', 42093, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 4, 'PAY_MODE', 'A', 191827, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 5, 'RISK_CODE', 'A', 206237, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendone_idx', 6, 'SEX', 'A', 403018, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 1, 'AGE', 'A', 77, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 2, 'DURATION', 'A', 4496, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 3, 'INSUREYEAR', 'A', 39778, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 4, 'PAY_MODE', 'A', 163841, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 5, 'RECEAGE', 'A', 319496, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 6, 'RISK_CODE', 'A', 360427, NULL, NULL, 'YES', 'BTREE', '', '');
INSERT INTO `<table_name>`(`Table`, `Non_unique`, `Key_name`, `Seq_in_index`, `Column_name`, `Collation`, `Cardinality`, `Sub_part`, `Packed`, `Null`, `Index_type`, `Comment`, `Index_comment`) VALUES ('pb_risk_dividend', 1, 'dividendtwo_idx', 7, 'SEX', 'A', 670930, NULL, NULL, 'YES', 'BTREE', '', '');
